# Решение систем линейных уравнений методом Крамера
$$
\begin{cases}
2x_1 - 4x_2 + 3x_3 = 1\\
x_1 - 2x_2 + 4x_3 = 3\\
3x_1 - x_2 + 5x_3 = 2
\end{cases}
$$

In [1]:
import numpy as np

In [2]:
a1 = [2, -4, 3]
a2 = [1, -2, 4]
a3 = [3, -1, 5]
b = [1, 3, 2]

В матричном виде эта система может быть записана как A ⋅ X = B, где
A - основная матрица системы, ее элементами являются коэффициенты при неизвестных переменных, B - матрица – столбец свободных членов

In [3]:
A = np.transpose(np.matrix([a1, a2, a3]))
print(A)

[[ 2  1  3]
 [-4 -2 -1]
 [ 3  4  5]]


In [4]:
B = np.transpose(np.matrix([b]))
print(B)

[[1]
 [3]
 [2]]


Определяем вспомогательные матрицы

In [5]:
A1 = np.transpose(np.matrix([b, a2, a3]))
print(A1)

[[ 1  1  3]
 [ 3 -2 -1]
 [ 2  4  5]]


In [6]:
A2 = np.transpose(np.matrix([a1, b, a3]))
print(A2)

[[ 2  1  3]
 [-4  3 -1]
 [ 3  2  5]]


In [7]:
A3 = np.transpose(np.matrix([a1, a2, b]))
print(A3)

[[ 2  1  1]
 [-4 -2  3]
 [ 3  4  2]]


Находим определители главной и вспомогательной матриц

In [8]:
A_det = round(np.linalg.det(A))
A1_det = round(np.linalg.det(A1))
A2_det = round(np.linalg.det(A2))
A3_det = round(np.linalg.det(A3))
print(f"|A| = {A_det}")
print(f"|A1| = {A1_det}")
print(f"|A2| = {A2_det}")
print(f"|A3| = {A3_det}")

|A| = -25
|A1| = 25
|A2| = 0
|A3| = -25


Находим неизвестные

In [9]:
x = A1_det / A_det
y = A2_det / A_det
z = A3_det / A_det
print(f"x = {x:.3f}")
print(f"y = {y:.3f}")
print(f"z = {z:.3f}")

x = -1.000
y = -0.000
z = 1.000


Сделаем проверку

In [10]:
znach = round(a1[0]*x + a2[0]*y + a3[0]*z)
print(f"{a1[0]}*({x:.3f}) + ({a2[0]})*({y:.3f}) + ({a3[0]})*({z:.3f}) = {znach}")
if znach == b[0]:
    print("Проверка пройдена")
else:
    print("Проверка не пройдена")

2*(-1.000) + (1)*(-0.000) + (3)*(1.000) = 1
Проверка пройдена
