# Задание 1
### Транспонирование матрицы

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [2]:
A = np.matrix('1 8 9; 32 18 -1')
print(A)

[[ 1  8  9]
 [32 18 -1]]


In [3]:
R = (A.T).T
print(R)

[[ 1  8  9]
 [32 18 -1]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [4]:
B = np.matrix('1 6 3; -4 2 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 2 28]
 [14 20]
 [12  4]]


In [5]:
print(R)

[[ 2 28]
 [14 20]
 [12  4]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [6]:
A = np.matrix('1 2; 5 1')
B = np.matrix('0 4; 7 1')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[14  7]
 [ 6 21]]


In [7]:
print(R)

[[14  7]
 [ 6 21]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [8]:
A = np.matrix(' 3 2 3; 3 17 1')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 9  9]
 [ 6 51]
 [ 9  3]]


In [9]:
print(R)

[[ 9  9]
 [ 6 51]
 [ 9  3]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [10]:
A = np.matrix('6 3; 3 2')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

3


In [11]:
print(format(A_T_det, '.9g'))

3
